export const SCORES = {
  INCORRECT: 0,
  CORRECT: 5,
} as const;

export const ELO_SYSTEM = {
  K_FACTOR: 32,
  MIN_ELO: 800,
  MAX_ELO: 2000,
  DEFAULT_ELO: 1200,
  EXPECTED_SCORE_DIVISOR: 400,
} as const;

export const STREAK_SYSTEM = {
  STREAK_START_POSITION: 3,
  BASE_MULTIPLIER: 1.0,
  STREAK_MULTIPLIER: 1.2,
  PROGRESSIVE_BONUS_INCREMENT: 0.05,
  PROGRESSIVE_MAX_BONUS: 0.3,
} as const;

export const RECENCY_SYSTEM = {
  DECAY_RATE: 0.95,
  MILLISECONDS_PER_DAY: 24 * 60 * 60 * 1000,
  SAME_DAY_THRESHOLD: 1,
  GRANULAR_THRESHOLD: 0.01,
} as const;

export const BOUNDS_SYSTEM = {
  DAMPENING_ZONE: 50,
  EXPONENTIAL_DAMPENING_ZONE: 100,
  MIN_DAMPENING_FACTOR: 0.1,
  EXPONENTIAL_MIN_DAMPENING_FACTOR: 0.05,
  QUADRATIC_EXPONENT: 2,
} as const;